name: tkinter App Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-python:
    runs-on: windows-latest

    steps:
      # Step 1: Get the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) {
            pip install -r requirements.txt
          }

      # Step 4: Run your main script
      - name: Run main file (timeout after 10 seconds)
        shell: pwsh
        run: |
            Start-Job { python main.py }
            Start-Sleep -Seconds 10
            Get-Job | Stop-Job
            Write-Output "Tkinter launched successfully."